#!/usr/bin/env bash
# Deploys one build to one stack: writes an immutable releases/<sha> directory, flips
# the current symlink to it atomically, recreates the containers, and gates on the
# served version matching the built artifact. A failed gate rolls back to whatever was
# live before this run started (symlink flip back plus a container recreate, the same
# operation rollback.sh performs by hand) and fails loudly rather than leaving a
# half-deployed stack.
#
# Ported from canonry-landing's scripts/deploy/release.sh (~/projects/personal/canonry-landing,
# the reference implementation named in issue #422), with the DATABASE_URL guard
# dropped: this repository has no database, so there is no secret to validate before
# the first container starts. The image variable is LANDING_IMAGE, and the default
# port and compose source point at this repository's own
# docker/deploy/compose.deploy.yml.
#
# Usage:
#   release.sh --stack prod --base /opt/apps/pitchbox-landing/prod \
#     --sha <commit-sha> --version vX.Y.Z --image ghcr.io/owner/pitchbox-landing@sha256:... \
#     [--compose-src PATH] [--secrets-file PATH] [--port 5184] \
#     [--timeout 90] [--interval 3] [--keep 5] [--deployed-by STRING]
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
script_dir="$(pwd)"
# shellcheck source=./lib.sh
. ./lib.sh

stack="" base="" sha="" version="" image="" compose_src="" secrets_file=""
port=5184 timeout=90 interval=3 keep=5 deployed_by="unspecified"

while [ $# -gt 0 ]; do
	case "$1" in
	--stack)
		stack="$2"
		shift 2
		;;
	--base)
		base="$2"
		shift 2
		;;
	--sha)
		sha="$2"
		shift 2
		;;
	--version)
		version="$2"
		shift 2
		;;
	--image)
		image="$2"
		shift 2
		;;
	--compose-src)
		compose_src="$2"
		shift 2
		;;
	--secrets-file)
		secrets_file="$2"
		shift 2
		;;
	--port)
		port="$2"
		shift 2
		;;
	--timeout)
		timeout="$2"
		shift 2
		;;
	--interval)
		interval="$2"
		shift 2
		;;
	--keep)
		keep="$2"
		shift 2
		;;
	--deployed-by)
		deployed_by="$2"
		shift 2
		;;
	*) die "unknown argument: $1" ;;
	esac
done

require_env stack base sha version image
require_cmd docker jq curl find

compose_src="${compose_src:-$script_dir/../../docker/deploy/compose.deploy.yml}"
secrets_file="${secrets_file:-$base/shared/secrets.env}"

[ -f "$compose_src" ] || die "compose source not found: $compose_src"
[ -f "$secrets_file" ] || die "secrets file not found: $secrets_file -- create it on prodbox out of band, this script never writes it"

deployed_json="$base/DEPLOYED.json"

# Capture what is live before touching anything, so a failed gate has something
# concrete to roll back to.
prev_release="" prev_version="" prev_commit="" prev_image=""
if [ -f "$deployed_json" ]; then
	prev_release=$(jq -r '.release // empty' "$deployed_json")
	prev_version=$(jq -r '.version // empty' "$deployed_json")
	prev_commit=$(jq -r '.commit // empty' "$deployed_json")
	prev_image=$(jq -r '.image // empty' "$deployed_json")
fi

new_dir="$(release_dir "$base" "$sha")"
[ -e "$new_dir" ] && die "release $sha already exists at $new_dir -- releases are immutable, nothing redeploys over one"

log "preparing release $sha ($version) for stack $stack under $new_dir"
mkdir -p "$base/releases" "$new_dir"
cp "$compose_src" "$new_dir/compose.yml"

# Bundle this exact version of the deploy tooling into the release too, so the
# rollback.sh a 3am incident reaches for (which points at BASE/current/scripts/deploy/...)
# always runs the script version that shipped with the release currently live, and a
# rollback rolls the tooling back along with the app.
mkdir -p "$new_dir/scripts"
cp -r "$script_dir" "$new_dir/scripts/deploy"

{
	cat "$secrets_file"
	printf '\n# Generated by release.sh, values pinned to this release. Do not edit.\n'
	printf 'LANDING_IMAGE=%s\n' "$image"
	printf 'APP_VERSION=%s\n' "$version"
	printf 'APP_COMMIT=%s\n' "$sha"
} >"$new_dir/.env"

lock_release "$new_dir"

log "flipping $base/current to releases/$sha"
atomic_symlink "releases/$sha" "$base/current"

log "recreating containers for stack $stack from $base/current"
if ! compose_cmd "$stack" "$base/current" up -d --remove-orphans; then
	log "compose up failed for release $sha"
	gate_ok=1
else
	url="http://127.0.0.1:${port}/healthz"
	log "waiting up to ${timeout}s for $url to serve version=$version commit=$sha"
	if poll_health "$url" "$version" "$sha" "$timeout" "$interval"; then
		gate_ok=0
	else
		gate_ok=1
	fi
fi

if [ "$gate_ok" -eq 0 ]; then
	log "health gate passed, release $sha is live for stack $stack"
	write_deployed_json "$deployed_json" "$stack" "$sha" "$version" "$sha" \
		"$image" "$deployed_by" "$prev_release" "healthy" ""
	"$script_dir/prune-releases.sh" --base "$base" --keep "$keep"
	exit 0
fi

log "health gate FAILED for release $sha, rolling back"

if [ -z "$prev_release" ] || [ ! -d "$(release_dir "$base" "$prev_release")" ]; then
	write_deployed_json "$deployed_json" "$stack" "$sha" "$version" "$sha" \
		"$image" "$deployed_by" "$prev_release" "failed" "no previous healthy release to roll back to -- stack $stack is left on the failed release, inspect manually"
	log "CRITICAL: no previous release to roll back to -- stack $stack is left on failed release $sha"
	exit 1
fi

log "flipping $base/current back to releases/$prev_release"
atomic_symlink "releases/$prev_release" "$base/current"
compose_cmd "$stack" "$base/current" up -d --remove-orphans || log "rollback compose up also failed -- inspect $base manually"

write_deployed_json "$deployed_json" "$stack" "$prev_release" "$prev_version" "$prev_commit" \
	"$prev_image" "$deployed_by" "$sha" "rolled_back" "auto-rollback: release $sha ($version) failed the health gate"

log "rolled back to $prev_release ($prev_version), failing this run"
exit 1
